### ISSUE TITLE
About examples and documentation

### ISSUE THREAD

**Issue by wTechArtist** [SirVeggie/comfyui-sv-nodes#1]
I am interested in this. Could you please provide examples and documentation?

**Comment by SirVeggie** [comment]
I'll create some example workflows with notes to explain them soon-ish. I'll comment here when I've done it.

**Comment by SirVeggie** [comment]
There's still some bugs I haven't had the time to fix, so in the meantime I recommend checking out the execution model inversion PR. It has even better functionality for dynamic branch control. Although it doesn't really have any examples either...
https://github.com/comfyanonymous/ComfyUI/pull/2666

**Comment by SirVeggie** [comment]
I have added explanations on how to use the flow nodes in the [wiki](https://github.com/SirVeggie/comfyui-sv-nodes/wiki). Sorry for taking this long.
